# ----------------------------------------------------------------------------
# sss - interactive SSH host picker (bash and zsh)
#
# Author:  Valentin Basin
# Version: 1.2.0
# Date:    2026-10-06
#
# Lists hosts from ~/.ssh/conf.d/*, grouped by file name, and from
# ~/.ssh/config (as [config]), and connects to the one selected in fzf.
# Recently used hosts are listed first.
#
# Usage:
#   sss                       pick a host interactively
#   sss <query>               pre-fill the search; connect directly on a
#                             single match
#   sss [<query>] -- <args>   pass <args> to ssh after the host: options
#                             (-L 8080:localhost:80) and/or a remote command
#
# Keys:
#   Enter   ssh to the host
#   Ctrl-T  ssh in a new terminal window
#   Ctrl-S  sftp to the host
#   Ctrl-F  yazi: tab 1 is the remote home, tab 2 the current directory
#   Ctrl-Y  copy the host alias to the clipboard
#   Ctrl-E  open the host's config file in $EDITOR
#
# Search comments: a "#:" line right above a Host block is shown next to the
# host and is searchable. Consecutive "#:" lines are joined.
#
#   #: home gateway, opnsense
#   Host gw-001
#
# yazi: its SFTP client does not read ssh_config, so Ctrl-F writes the host's
# resolved settings to yazi's vfs.toml, inside a "# >>> sss" ... "# <<< sss"
# block. ProxyJump, ProxyCommand and Match are not supported by yazi.
# ----------------------------------------------------------------------------

# Write an [sftp.<name>] section for host $1 to yazi's vfs.toml and print
# <name>. Only the sss block is rewritten; a section with the same name
# defined by hand outside the block takes precedence and is used as is.
_sss_yazi_vfs() {
  local host="$1"
  local conf="${YAZI_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/yazi}/vfs.toml"
  local name k v f hostname user port key section

  # yazi requires kebab-case names of up to 20 characters.
  name=$(printf '%s' "$host" | tr 'A-Z' 'a-z' |
    sed -E 's/[^a-z0-9]+/-/g; s/^-+//' | cut -c1-20 | sed -E 's/-+$//')
  [ -n "$name" ] || { echo "sss: cannot derive a yazi name for '$host'" >&2; return 1; }

  mkdir -p "${conf%/*}" && touch "$conf" || return 1
  if awk -v s="[sftp.$name]" '
      /^# >>> sss/ { inb = 1 } /^# <<< sss/ { inb = 0 }
      !inb && $0 == s { found = 1 } END { exit !found }' "$conf"; then
    printf '%s\n' "$name"
    return
  fi

  # Effective settings, including Include and "Host *" blocks.
  while read -r k v; do
    case "$k" in
      hostname) hostname=$v ;;
      user) user=$v ;;
      port) port=$v ;;
      identityfile)
        # ssh -G lists default keys too; take the first one that exists.
        case "$v" in "~/"*) f="$HOME/${v#\~/}" ;; *) f=$v ;; esac
        [ -z "$key" ] && [ -f "$f" ] && key=$f
        ;;
    esac
  done <<EOF
$(command ssh -G "$host" 2>/dev/null)
EOF
  [ -n "$hostname" ] || { echo "sss: cannot resolve '$host'" >&2; return 1; }

  # A key that needs a passphrase is left to ssh-agent instead.
  if [ -n "$key" ] && ! ssh-keygen -y -P '' -f "$key" >/dev/null 2>&1; then
    key=
  fi

  section="[sftp.$name]
host = \"$hostname\"
user = \"$user\"
port = ${port:-22}
${key:+key_file = \"$key\"
}
"
  # Replace this host's section inside the block, or append a new block.
  SSS_SECTION="$section" awk -v s="[sftp.$name]" '
    /^# >>> sss/ { inb = 1; found = 1; print; next }
    inb && /^# <<< sss/ { printf "%s", ENVIRON["SSS_SECTION"]; inb = 0; skip = 0; print; next }
    inb && /^\[/ { skip = ($0 == s) }
    inb && skip { next }
    { print }
    END {
      if (!found)
        printf "\n# >>> sss (generated by sss, edits are overwritten)\n%s# <<< sss\n", ENVIRON["SSS_SECTION"]
    }
  ' "$conf" > "$conf.tmp" && chmod 600 "$conf.tmp" && mv "$conf.tmp" "$conf" || return 1

  printf '%s\n' "$name"
}

sss() {
  command -v fzf >/dev/null 2>&1 || { echo "sss: fzf not found" >&2; return 1; }

  local dir="$HOME/.ssh/conf.d"
  local hist="${XDG_CACHE_HOME:-$HOME/.cache}/sss/history"
  local cfg="$HOME/.ssh/config"
  local tab="$(printf '\t')"
  local query="" parse out rc key line host file lineno vfs hint

  # Words before "--" form the query; everything after it stays in "$@"
  # and is passed to ssh.
  while [ $# -gt 0 ]; do
    [ "$1" = "--" ] && { shift; break; }
    query="${query:+$query }$1"
    shift
  done

  # Key hints for the fzf footer: bold yellow key, dimmed action.
  hint=$(
    for kv in "enter:ssh" "^t:window" "^s:sftp" "^f:yazi" "^y:copy" "^e:edit"; do
      printf '\033[1;33m%s\033[0m \033[2m%s\033[0m   ' "${kv%%:*}" "${kv#*:}"
    done
  )

  mkdir -p "${hist%/*}" && touch "$hist" || return 1

  # Print "<category>\t<host>\t<file>\t<line>\t<comment>" for every host.
  # The category is the file path relative to d, or "fixed" if set.
  # Handles "Host a b", "host a", indented lines and "Host=a"; skips
  # wildcard and negated patterns (*, ?, !).
  parse='
    FNR == 1 { c = "" }
    /^[ \t]*#:/ {
      s = $0
      sub(/^[ \t]*#:[ \t]*/, "", s)
      gsub(/\t/, " ", s)
      c = (c == "" ? s : c " " s)
      next
    }
    tolower($1) ~ /^host(=|$)/ {
      cat = (fixed != "" ? fixed : substr(FILENAME, length(d) + 1))
      s = $0
      sub(/^[ \t]*[Hh][Oo][Ss][Tt][ \t]*=?[ \t]*/, "", s)
      n = split(s, a, /[ \t]+/)
      for (i = 1; i <= n; i++)
        if (a[i] != "" && a[i] !~ /[*?!]/)
          printf "%s\t%s\t%s\t%s\t%s\n", cat, a[i], FILENAME, FNR, c
      c = ""
      next
    }
    # Any other non-blank line detaches a pending comment.
    NF { c = "" }
  '

  # Build "<host>\t<file>\t<line>\t<display>" records; fzf shows only the
  # display part. -L makes find follow symlinked files.
  out=$(
    {
      find -L "$dir" -type f -exec awk -v d="$dir/" "$parse" {} + 2>/dev/null
      [ -f "$cfg" ] && awk -v fixed=config "$parse" "$cfg"
    } |
      # Group by category, keeping the in-file host order.
      sort -t "$tab" -k1,1 -s |
      # Prefix each record with its history rank (0 = never used).
      awk -F'\t' -v h="$hist" '
        FILENAME == h { rank[$0] = FNR; next }
        { print ($2 in rank ? rank[$2] : 0) "\t" $0 }
      ' "$hist" - |
      # Most recently used first; unused hosts keep the category order.
      sort -t "$tab" -k1,1nr -s |
      awk -F'\t' '{
        printf "%s\t%s\t%s\t\033[34m[%-12s]\033[0m %-20s \033[90m%s\033[0m\n",
          $3, $4, $5, $2, $3, $6
      }' |
      fzf --ansi \
        --delimiter="$tab" \
        --with-nth=4.. \
        --height=40% \
        --layout=reverse \
        --border \
        --prompt="SSH > " \
        --footer="$hint" \
        --footer-border=rounded \
        --footer-label=" keys " \
        --color=footer-border:8,footer-label:8 \
        --expect=ctrl-t,ctrl-s,ctrl-f,ctrl-y,ctrl-e \
        --query="$query" \
        ${query:+--select-1} ${query:+--exit-0} \
        --preview-window=right:40% \
        --preview 'command ssh -G {1} 2>/dev/null | grep -E -i "^(hostname|user|port|identityfile|proxyjump)"'
  )
  rc=$?
  if [ $rc -ne 0 ]; then
    [ $rc -eq 1 ] && [ -n "$query" ] && echo "sss: no host matches '$query'" >&2
    return $rc
  fi

  # fzf prints the pressed key (empty for Enter) and then the selected line.
  key=${out%%$'\n'*}
  line=${out#*$'\n'}
  host=${line%%"$tab"*}
  line=${line#*"$tab"}
  file=${line%%"$tab"*}
  line=${line#*"$tab"}
  lineno=${line%%"$tab"*}
  [ -n "$host" ] || return 1

  case "$key" in
    ctrl-y)
      if command -v wl-copy >/dev/null 2>&1; then printf '%s' "$host" | wl-copy
      elif command -v xclip >/dev/null 2>&1; then printf '%s' "$host" | xclip -selection clipboard
      elif command -v pbcopy >/dev/null 2>&1; then printf '%s' "$host" | pbcopy
      else echo "sss: no clipboard tool found" >&2; return 1
      fi
      echo "Copied: $host"
      return
      ;;
    ctrl-e)
      # eval lets $EDITOR carry its own arguments in both bash and zsh.
      eval "${EDITOR:-vi} \"+\$lineno\" \"\$file\""
      return
      ;;
    ctrl-f)
      command -v yazi >/dev/null 2>&1 || { echo "sss: yazi not found" >&2; return 1; }
      vfs=$(_sss_yazi_vfs "$host") || return 1
      ;;
  esac

  # Move the host to the end of the history and keep the file short.
  {
    grep -vxF -- "$host" "$hist"
    printf '%s\n' "$host"
  } > "$hist.tmp" && tail -n 200 "$hist.tmp" > "$hist"
  rm -f "$hist.tmp"

  case "$key" in
    ctrl-t)
      # Prefer the current terminal, fall back to the desktop default.
      # The subshell keeps the job out of the shell's job table.
      if [ -n "$KITTY_WINDOW_ID" ] && command -v kitty >/dev/null 2>&1; then
        ( kitty ssh "$host" "$@" >/dev/null 2>&1 & )
      elif [ -n "$GHOSTTY_RESOURCES_DIR" ] && command -v ghostty >/dev/null 2>&1; then
        ( ghostty -e ssh "$host" "$@" >/dev/null 2>&1 & )
      elif command -v xdg-terminal-exec >/dev/null 2>&1; then
        ( xdg-terminal-exec ssh "$host" "$@" >/dev/null 2>&1 & )
      else
        echo "sss: no terminal found for a new window" >&2; return 1
      fi
      echo "Opened $host in a new window"
      return
      ;;
    ctrl-s|ctrl-f)
      [ $# -gt 0 ] && echo "sss: arguments after -- are only used for ssh" >&2
      if [ "$key" = ctrl-s ]; then
        sftp "$host"
      else
        # The first tab is the active one.
        command yazi "sftp://$vfs/" "$PWD"
      fi
      return
      ;;
  esac

  # Set the terminal title while connected, then reset it.
  [ -t 1 ] && printf '\033]0;SSH: %s\007' "$host"
  echo "Connecting to $host..."
  # ssh accepts options after the host too, so "$@" may mix both.
  ssh "$host" "$@"
  rc=$?
  [ -t 1 ] && printf '\033]0;%s\007' "${SHELL##*/}"
  return $rc
}
